_wandb:
    value:
        cli_version: 0.19.1
        code_path: code/manage.py
        m: []
        python_version: 3.9.6
        t:
            "1":
                - 55
                - 95
            "2":
                - 55
                - 95
            "3":
                - 23
                - 55
            "4": 3.9.6
            "5": 0.19.1
            "8":
                - 5
            "12": 0.19.1
            "13": darwin-arm64
